feat(fe): migrate to nextjs

diff --git a/Dockerfile.fe b/Dockerfile.fe
--- a/Dockerfile.fe
+++ b/Dockerfile.fe
@@ -1,47 +1,49 @@
-FROM node:16-alpine as build-stage
+FROM node:16-alpine AS deps
+RUN apk add --no-cache libc6-compat
 
 ARG BE_API_URL
 ARG RECAPTCHA_SITE_KEY
-ARG FE_NOTES_HTML_PATH
-ARG FE_TILS_HTML_PATH
 
-ENV VITE_APP_API_URL=${BE_API_URL}
-ENV VITE_APP_NOTES_HTML_PATH=${FE_NOTES_HTML_PATH}
-ENV VITE_APP_TILS_HTML_PATH=${FE_TILS_HTML_PATH}
-ENV VITE_APP_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
+ENV NEXT_PUBLIC_API_URL=${BE_API_URL}
+ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
 
-WORKDIR /apps
-COPY ./admin-fe/package.json ./admin-fe/package-lock.json ./admin-fe/
-RUN npm install --prefix ./admin-fe
+WORKDIR /app
 
-COPY ./fe/package.json ./fe/package-lock.json ./fe/
-RUN npm install --prefix ./fe
+COPY ./fe/package.json ./fe/yarn.lock* ./fe/package-lock.json* ./fe/pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-COPY ./admin-fe ./admin-fe
-RUN npm run build --prefix ./admin-fe
 
-COPY ./fe ./fe
-RUN npm run build --prefix ./fe
+# Rebuild the source code only when needed
+FROM node:16-alpine AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY ./fe/. .
 
-# production
-FROM nginx:stable-alpine as production-stage
+RUN npm run build
 
-ARG FE_DIR
-ARG FE_DOMAIN
-ARG ADMIN_FE_DOMAIN
-ARG BE_DOMAIN
+# Production image, copy all the files and run next
+FROM node:16-alpine AS runner
+WORKDIR /app
 
-# env for nginx template
-ENV FE_DIR=${FE_DIR}
-ENV ADMIN_FE_DIR=/apps/admin-fe
-ENV FE_DOMAIN=${FE_DOMAIN}
-ENV ADMIN_FE_DOMAIN=${ADMIN_FE_DOMAIN}
-ENV BE_DOMAIN=${BE_DOMAIN}
+ENV NODE_ENV production
 
-COPY --from=build-stage /apps/admin-fe/dist/. ${ADMIN_FE_DIR}
-COPY --from=build-stage /apps/fe/dist/. ${FE_DIR}
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-# TODO use template for setting env: Domain, directory
-COPY ./nginx-templates /etc/nginx/templates
+ENV NODE_ENV=production
+COPY ./fe/. .
+COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
+COPY --from=builder /app/node_modules ./node_modules
 
-CMD ["nginx", "-g", "daemon off;"]
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
+
+CMD ["yarn", "start"]
